"""Reproduce the small, real dual-RIS Future 1x1 demonstration.

The scene remains a normal Scene v1 JSON.  Commands are generated by the
existing Controller-only dual-RIS Focus helper and saved in a separate result
manifest because Scene v1 intentionally does not persist runtime patterns.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import json
import time

import numpy as np

from airmirror_future import (
    FAST_1X1_RIS_COEFFICIENT_MODEL,
    SimulationEngine,
    evaluate_dual_ris_command,
    generate_dual_ris_coordinated_patterns,
)
from airmirror_future.scene.serialization import load_scene


def _complex(value: complex) -> dict[str, float]:
    return {"real": float(value.real), "imag": float(value.imag)}


def _result(result: object, patterns: dict[str, np.ndarray]) -> dict[str, object]:
    return {
        "commands_rad": {
            identifier: [float(value) for value in pattern]
            for identifier, pattern in patterns.items()
        },
        "baseline_channel": _complex(result.los_channel + result.wall_channel),
        "los_channel": _complex(result.los_channel),
        "wall_channel": _complex(result.wall_channel),
        "ris_channel": _complex(result.ris_channel),
        "total_channel": _complex(result.total_channel),
        "received_power_w": float(result.received_power_w),
        "received_power_dbm": float(result.received_power_dbm),
        "snr_db": float(result.snr_db),
    }


def build_demo(scene_path: Path) -> dict[str, object]:
    scene = load_scene(scene_path)
    engine = SimulationEngine(coefficient_model=FAST_1X1_RIS_COEFFICIENT_MODEL)
    ris_ids = tuple(ris.id for ris in scene.ris_surfaces)
    if len(ris_ids) != 2:
        raise ValueError("demo scene must contain exactly two RIS surfaces")

    started = time.perf_counter()
    no_ris = evaluate_dual_ris_command(scene, {}, engine=engine)
    single_results: dict[str, dict[str, object]] = {}
    single_commands: dict[str, dict[str, np.ndarray]] = {}
    for ris_id in ris_ids:
        focused = generate_dual_ris_coordinated_patterns(
            scene, engine=engine, ris_ids=(ris_id,)
        )
        single_commands[ris_id] = focused.patterns
        single_results[ris_id] = _result(
            evaluate_dual_ris_command(scene, focused.patterns, engine=engine),
            focused.patterns,
        )

    dual_focus = generate_dual_ris_coordinated_patterns(
        scene, engine=engine, ris_ids=ris_ids
    )
    dual = evaluate_dual_ris_command(scene, dual_focus.patterns, engine=engine)
    return {
        "schema": "airmirror_future_dual_ris_demo/1",
        "scene_file": str(scene_path.as_posix()),
        "target": {
            "tx_id": scene.transmitter().id,
            "rx_id": scene.receiver().id,
            "rx_position_m": {
                "x": float(scene.receiver().position.x),
                "y": float(scene.receiver().position.y),
                "z": float(scene.receiver().position.z),
            },
        },
        "ris": [
            {
                "id": ris.id,
                "generation": ris.generation,
                "enabled": bool(ris.enabled),
                "position_m": {
                    "x": float(ris.position.x),
                    "y": float(ris.position.y),
                    "z": float(ris.position.z),
                },
                "yaw_rad": float(ris.yaw_rad),
                "width_m": float(ris.width_m),
                "height_m": float(ris.height_m),
                "control_grid": [int(ris.nx), int(ris.ny)],
                "phase_bits": ris.phase_bits,
                "reflection_efficiency": float(ris.reflection_efficiency),
            }
            for ris in scene.ris_surfaces
        ],
        "coefficient_model": {
            "identity": FAST_1X1_RIS_COEFFICIENT_MODEL.identity,
            "quadrature_identity": FAST_1X1_RIS_COEFFICIENT_MODEL.quadrature_identity,
        },
        "cases": {
            "no_ris": _result(no_ris, {}),
            "single_ris": single_results,
            "dual_ris": {
                **_result(dual, dual_focus.patterns),
                "focus_rounds": int(dual_focus.rounds),
                "focus_converged": bool(dual_focus.converged),
            },
        },
        "runtime_s": float(time.perf_counter() - started),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--scene",
        type=Path,
        default=Path("scenes/future_dual_ris_demo.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/demos/future_dual_ris_demo_1x1.json"),
    )
    args = parser.parse_args()
    payload = build_demo(args.scene)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps({"output": str(args.output), "runtime_s": payload["runtime_s"]}))


if __name__ == "__main__":
    main()
